spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  flyway:
    enabled: true
    locations:
      - "classpath:db/migration"
    baseline-on-migrate: true
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 16
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ" # Преобразование даты
    deserialization:
      fail-on-unknown-properties: false # Пропуск неизвестных значений от фронта
    default-property-inclusion: non_null # Удаление нулл полей

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

openapi:
  gateway-url: ${GATEWAY_URL:http://localhost:8000}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:must-be-overridden}
      expiration: 900000 # 15 минут
      refresh-token:
        expiration: 604800000 # 7 дней

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    root: INFO