spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: 5
      connection-timeout: 10000 # 10 сек таймаута
      idle-timeout: 300000 # 5 мин
      max-lifetime: 1800000 # 30 мин
      leak-detection-threshold: 30000 # 30 сек

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 900000 # 15 минут
      refresh-token:
        expiration: 604800000 # 7 дней

logging:
  level:
    root: WARN
    com.spotilike: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
    com.zaxxer.hikari: INFO