spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          routes:
            - id: user-service
              uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**
              filters:
                - StripPrefix=0

gateway:
  cors-allowed-origins:
    - "*"
  cors-allow-credentials: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:bG9jYWwtZGV2LXNlY3JldC1rZXktMzItYnl0ZXMtbG9uZyE=}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.spotilike.gateway: DEBUG