spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
          routes:
            - id: user-service-api-docs
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - RewritePath=/v3/api-docs/user-service, /api-docs

            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**

app-gateway:
  cors-allowed-origins:
    - "*"
  cors-allow-credentials: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:bG9jYWwtZGV2LXNlY3JldC1rZXktMzItYnl0ZXMtbG9uZyE=}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.spotilike.gateway: DEBUG