CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uc_roles_name UNIQUE (name)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    avatar_url    VARCHAR(512),
    is_verified   BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE TABLE tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    token_hash  VARCHAR(512)                            NOT NULL,
    ip_address  VARCHAR(45),
    device_info VARCHAR(512)                            NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_revoked  BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_tokens PRIMARY KEY (id),
    CONSTRAINT uc_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_tokens_on_user FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id)
        REFERENCES roles (id)
);

CREATE INDEX idx_users_email
    ON users (email);

CREATE INDEX idx_tokens_user_id
    ON tokens (user_id);

CREATE INDEX idx_tokens_token_hash
    ON tokens (token_hash);

CREATE INDEX idx_tokens_user_revoked
    ON tokens (user_id, is_revoked);