name: Spotilike CI/CD

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  shared-libs:
    name: Build & Test Shared Libraries
    runs-on: ubuntu-latest

    steps:
      # Скачивание кода
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка JDK
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      # Установка прав
      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      # Билды и тесты
      - name: Build & Test shared-exception
        run: |
          cd backend
          ./gradlew :shared-libs:shared-exception:build --no-daemon

      - name: Build & Test shared-security
        run: |
          cd backend
          ./gradlew :shared-libs:shared-security:build --no-daemon

  microservices:
    name: Build & Test ${{ matrix.service }}
    runs-on: ubuntu-latest

    # Сборка только после успешного shared-libs
    needs: shared-libs

    strategy:
      fail-fast: false
      matrix:
        service:
          - name: 'user-service'
            gradle-path: ':user-service'
          - name: 'gateway-service'
            gradle-path: ':gateway-service'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Build and Test ${{ matrix.service.name }}
        run: |
          cd backend
          ./gradlew ${{ matrix.service.gradle-path }}:build --no-daemon